### ISSUE TITLE
Can't clear scoresN.txt

### ISSUE THREAD

**Issue by luckalgorithm** [StatusCritical/benchmark_tool#10]
Maybe make it so you can clear the score files sometime?

**Comment by aerogull** [comment]
Yeah, I could do that, it's not too hard.

**Comment by aerogull** [comment]
Actually, would you like to be able to clear only one file or all files?

**Comment by luckalgorithm** [comment]
One at a time and/or all at once.

**Comment by aerogull** [comment]
Ok, got it.
